services:
  db:
    image: postgres:17.4
    container_name: airbnb_postgres
    restart: always
    environment:
      POSTGRES_USER: airbnb
      POSTGRES_PASSWORD: airbnb
      POSTGRES_DB: airbnb_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
#      - ./views.sql:/docker-entrypoint-initdb.d/views.sql
    ports:
      - 2345:5432
volumes:
  pgdata: